// apps/react-frontend/src/pages/landing-page/components/landing-page/landing-page.tsx
import {
  LandingPageBanner,
  LandingPageFeatureCard,
  LandingPageFooter,
  LandingPageHeader,
} from '@api-assistant/landing-page-fe';
import styles from './landing-page.module.scss';
import {
  MdOutlineManageAccounts,
  MdOutlineCloudUpload,
  MdOutlineDataObject,
  MdOutlineFavorite,
} from 'react-icons/md';
import { useContext } from 'react';
import { ProfileContext } from '@api-assistant/accounts-fe';
import { useDispatch } from 'react-redux';
import { AppDispatch } from 'apps/react-frontend/src/store/app.state';
import { logoutAccount } from '../../../accounts/store/effects';

/* eslint-disable-next-line */
export interface LandingPageProps {}

export function LandingPage(props: LandingPageProps) {

  const { isAuthenticated } = useContext(ProfileContext);

  const dispatch = useDispatch<AppDispatch>();

  const handleLogout = () => {
    dispatch(logoutAccount())
  }

  return (
    <div className={styles['landing-page']}>
      <LandingPageHeader handleLogout={handleLogout} isUserLoggedIn={isAuthenticated} />
      <LandingPageBanner />
      <h1 style={{ textAlign: 'center', padding: '2rem' }}>Features</h1>
      <div className={styles['landing-page__feature_cards']}>
        <LandingPageFeatureCard
          icon={<MdOutlineDataObject fontSize={'50px'} />}
          title="CRUD Declaratively"
          description="Build MongoDB queries in Frontend and API Assistant executes for you"
        />
        <LandingPageFeatureCard
          icon={<MdOutlineManageAccounts fontSize={'50px'} />}
          title="Welcome users at ease"
          description="Integrate Username and Password authentication in minutes"
        />
        <LandingPageFeatureCard
          icon={<MdOutlineCloudUpload fontSize={'50px'} />}
          title="Scalable object store"
          description="Upload your user files without worrying about infrastructure"
        />
        <LandingPageFeatureCard
          icon={<MdOutlineFavorite fontSize={'50px'} />}
          title="Ultra smooth UI"
          description="Manage your application's backend with simple and smooth UI"
        />
      </div>
      <div className={styles['landing-page__footer']}>
        <LandingPageFooter isUserLoggedIn={isAuthenticated} />
      </div>
    </div>
  );
}

export default LandingPage;

// apps/frontend/src/modules/landing-page/components/landing-page/landing-page.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { RouterModule } from "@angular/router";

interface LandingPageFeatureCard {
    id: number;
    title: string;
    description: string;
}

@Component({
    selector: "api-assistant-landing-page",
    templateUrl: "./landing-page.component.html",
    styleUrls: ["./landing-page.component.scss"],
    standalone: true,
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [
        CommonModule,
        RouterModule
    ]
})
export class LandingPageComponent {

    constructor(
    ) {}

    
    public LANDING_PAGE_FEATURES: LandingPageFeatureCard[] = [
        {
            id: 1,
            title: "Queries on Frontend",
            description: "Write queries in frontend and API Assistant executes it for you"
        },
        {
            id: 2,
            title: "Welcome users at ease",
            description: "Integrate username-password authentication in minutes"
        },
        {
            id: 3,
            title: "Upload files",
            description: "Store user uploaded files without worrying about infrastructure"
        },
        {
            id: 4,
            title: "Clean and intutive UI",
            description: "Explore your data and files with simple and smooth UI"
        }
    ]

    public trackFeatureCard(_: number, card: LandingPageFeatureCard): number {
        return card.id;
    }

}
<main class="landing-page">
    <header class="landing-page__header">
        <ng-container *ngIf="false; else loginLinks">
            <a routerLink="/app/projects">Go to app</a>
        </ng-container>
        <ng-template #loginLinks>
            <a routerLink="/accounts/signup">Signup</a>
            <a routerLink="/accounts/login">Login</a>
        </ng-template>
    </header>
    <div class="landing-page__banner">
        <h1>API Assistant</h1>
        <h4>Declarative Backend for trivial apps</h4>
    </div>
    <div class="landing-page__features">
        <h1>Features</h1>
        <ng-container *ngFor="let featureCard of LANDING_PAGE_FEATURES; trackBy: trackFeatureCard">
            <div class="landing-page__feature-card">
                <h6>{{ featureCard.title }}</h6>
                <span style="font-weight: 300;">{{ featureCard.description }}</span>
            </div>
        </ng-container>
    </div>
    <footer class="landing_page__footer">
        <span>
            Want to build application with API Assistant? 
            <a routerLink="/accounts/signup">Signup here</a>
        </span>

    </footer>
</main>
