// apps/frontend/src/modules/landing-page/components/landing-page/landing-page.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { RouterModule } from "@angular/router";

interface LandingPageFeatureCard {
    id: number;
    title: string;
    description: string;
}

@Component({
    selector: "api-assistant-landing-page",
    templateUrl: "./landing-page.component.html",
    styleUrls: ["./landing-page.component.scss"],
    standalone: true,
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [
        CommonModule,
        RouterModule
    ]
})
export class LandingPageComponent {

    constructor(
    ) {}

    
    public LANDING_PAGE_FEATURES: LandingPageFeatureCard[] = [
        {
            id: 1,
            title: "Queries on Frontend",
            description: "Write queries in frontend and API Assistant executes it for you"
        },
        {
            id: 2,
            title: "Welcome users at ease",
            description: "Integrate username-password authentication in minutes"
        },
        {
            id: 3,
            title: "Upload files",
            description: "Store user uploaded files without worrying about infrastructure"
        },
        {
            id: 4,
            title: "Clean and intutive UI",
            description: "Explore your data and files with simple and smooth UI"
        }
    ]

    public trackFeatureCard(_: number, card: LandingPageFeatureCard): number {
        return card.id;
    }

}
<main class="landing-page">
    <header class="landing-page__header">
        <ng-container *ngIf="false; else loginLinks">
            <a routerLink="/app/projects">Go to app</a>
        </ng-container>
        <ng-template #loginLinks>
            <a routerLink="/accounts/signup">Signup</a>
            <a routerLink="/accounts/login">Login</a>
        </ng-template>
    </header>
    <div class="landing-page__banner">
        <h1>API Assistant</h1>
        <h4>Declarative Backend for trivial apps</h4>
    </div>
    <div class="landing-page__features">
        <h1>Features</h1>
        <ng-container *ngFor="let featureCard of LANDING_PAGE_FEATURES; trackBy: trackFeatureCard">
            <div class="landing-page__feature-card">
                <h6>{{ featureCard.title }}</h6>
                <span style="font-weight: 300;">{{ featureCard.description }}</span>
            </div>
        </ng-container>
    </div>
    <footer class="landing_page__footer">
        <span>
            Want to build application with API Assistant? 
            <a routerLink="/accounts/signup">Signup here</a>
        </span>

    </footer>
</main>

// apps/frontend/src/modules/landing-page/components/landing-page/LandingPage.tsx
import { APP_CONFIG } from "apps/frontend/src/constants";
import "./LandingPage.scss";
import { LandingPageFeatureCard } from "../landing-page-feature-card/LandingPageFeatureCard";
import { Link } from "react-router-dom";
import { LandingPageHeader } from "../landing-page-header/LandingPageHeader";

export function LandingPage() {
    const features: {name: string, id: number, description: string}[] = [
        {
            id: 1,
            name: "Zero Backend code",
            description: `Declaratively create and query application data from Frontend.`
        },
        {
            id: 2,
            name: "Welcome users in minutes",
            description: "Integrate username and password authentication in minutes."
        },
        {
            id: 3,
            name: "Upload files",
            description: "Allow users to upload files without worrying about infrastructure."
        },
        {
            id: 4,
            name: "Simple and Clean UI",
            description: `Explore application data and files in simple and elegant UI`
        }
    ]
    return (
        <section className="w-100 d-flex flex-column landing-page">
            <LandingPageHeader />
            <div className="landing-page-app-banner d-flex flex-column 
                align-items-center justify-content-around">
                <h1>{APP_CONFIG.NAME}</h1>
                <h3>{APP_CONFIG.SLOGAN}</h3>
            </div>
            <div className="mt-3 w-100 landing-page-feature-cards">
                {features.map(feature => 
                    <LandingPageFeatureCard 
                        name={feature.name} 
                        key={feature.id}
                        description={feature.description} 
                    />
                )}
            </div>
            <div className="landing-page-try-today-banner">
                <span>
                    Want to build application with {APP_CONFIG.NAME}?
                    <Link to={"/accounts/signup"}> Signup here</Link>
                </span>
            </div>
        </section>        
    )
}
