// apps/react-frontend/src/pages/accounts/components/accounts-shell/accounts-shell.tsx
import { Link, Outlet, useNavigate } from 'react-router-dom';
import styles from './accounts-shell.module.scss';
import { useContext, useEffect } from 'react';
import { ProfileContext } from '@api-assistant/accounts-fe';

/* eslint-disable-next-line */
export interface AccountsShellProps {}

export function AccountsShell(props: AccountsShellProps) {

  const profile = useContext(ProfileContext);

  const navigate = useNavigate()

  useEffect(() =>{
    if(profile !== null) {
      navigate("/")
    }
  }, [profile])

  return (
    <div className={styles['accounts-shell']}>
      <div className={styles['accounts-shell__banner']}>
        <Link to={'/'}>API Assistant</Link>
        <h4>Declarative backend for trivial apps</h4>
      </div>

      <div className={styles['accounts-shell__outlet']}>
        <Outlet />
      </div>
    </div>
  );
}

export default AccountsShell;

// apps/frontend/src/modules/accounts/components/accounts-shell/accounts-shell.component.ts
import { Component } from '@angular/core';
import { RouterModule } from "@angular/router";
import { AccountRoutesHeaderComponent } from '../account-routes-header/account-routes-header.component';

@Component({
  selector: 'api-assistant-accounts-shell',
  templateUrl: './accounts-shell.component.html',
  styleUrls: ['./accounts-shell.component.scss'],
  standalone: true,
  imports: [
    RouterModule,
    AccountRoutesHeaderComponent
  ]
})
export class AccountsShellComponent {}

<main class="accounts-shell">
    <div class="accounts-shell__banner">
        <div>
            <h1>
                <a routerLink="/">API Assistant</a>
            </h1>
            <h6>Declarative Backend for trivial apps</h6>
        </div>
    </div>
    <div class="accounts-shell__router">
        <api-assistant-account-routes-header class="account-routes-header">
        </api-assistant-account-routes-header>
        <div class="router-outlet__content">
            <router-outlet></router-outlet>
        </div>
    </div>
</main>
