// apps/frontend/src/modules/accounts/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { loginAccount } from '../../store/accounts.actions';
import { isAccountsAPIInProgressSelector } from '../../store/accounts.selectors';
import { AppState } from '../../../app/store/appstate';

@Component({
  selector: 'api-assistant-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent {

  constructor(
    private formBuilder: FormBuilder,
    private store: Store<AppState>
  ) {}

  public isAccountsAPIInProgress$ = this.store.select(state => state.accounts.isAccountsAPIInProgress)

  public loginForm: FormGroup = this.createLoginForm();

  private createLoginForm(): FormGroup {
    return this.formBuilder.group({
      emailId: this.formBuilder.control(''),
      password: this.formBuilder.control('')
    })
  }


  public handleLogin() {
    this.store.dispatch(loginAccount(this.loginForm.value))
  }
}

// apps/react-frontend/src/pages/accounts/components/login/login.tsx
import { useDispatch } from 'react-redux';
import styles from './login.module.scss';
import { LoginForm, LoginFormValue } from "@api-assistant/accounts-fe"
import { AppDispatch } from 'apps/react-frontend/src/store/app.state';
import { loginAccount } from '../../store/effects';

/* eslint-disable-next-line */
export interface LoginProps {}

export function Login() {

  const dispatch = useDispatch<AppDispatch>()

  const handleLogin = (credentials: LoginFormValue) => {
    dispatch(loginAccount({emailId: credentials.emailId, password: credentials.password}))
  }

  return (
    <div className={styles['login-container']}>
      <LoginForm handleLogin={handleLogin} />
    </div>
  );
}

export default Login;
