// apps/frontend/src/modules/accounts/pages/signup/signup.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'api-assistant-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss'],
})
export class SignupComponent {}

<div class="signup">
	<form class="signup__form">
		<h4>Signup</h4>
		<input sw-input type="email" placeholder="Email ID" />
		<input sw-input type="text" placeholder="Username" />
		<input sw-input type="password" placeholder="Password" />
		<button sw-primary-button>Create account</button>
	</form>
	<span>Already have an account? <a routerLink="/accounts/login">Login here</a></span>
</div>

// apps/frontend/src/modules/accounts/components/signup/Signup.tsx
import { Link } from "react-router-dom";
import { Input, Button } from "@praveenkumarcp/reacteasy";
import "./Signup.scss";

export function Signup() {
    return (
        <div 
            className="h-100 w-100 d-flex flex-column justify-content-center align-items-center">
            <form className="signup-form d-flex flex-column justify-content-between">
                <h3 className="align-self-start">Welcome</h3>
                <Input id="emailId" type="email" placeholder="Email ID" />
                <Input id="username" type="text" placeholder="User name" />
                <Input id="password" type="password" placeholder="Password" />
                <Button className="mt-3" group="primary" label="CREATE ACCOUNT" />
                <span className="align-self-center">
                    Already have an account? 
                    <Link to={"/accounts/login"}> Login here</Link>
                </span>
            </form>
        </div>
    )
}
